version: '3.8'

services:
  nginx:
    image: nginx:latest
    container_name: wp_nginx
    restart: always
    ports:
      - '8000:80'
    volumes:
      - ../wordpress:/var/www/html
      - ../theme:/var/www/html/wp-content/themes/
      - ../courses:/var/www/html/wp-content/plugins/courses/ # Mount plugin directory
      - ../plc-plugin:/var/www/html/wp-content/plugins/plc-plugin/ # Mount plugin directory
      - ../docker/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
      - db

  php:
    build:
      context: ../docker
      dockerfile: Dockerfile.php
    container_name: wp_php
    restart: always
    volumes:
      - ../wordpress:/var/www/html
      - ../theme:/var/www/html/wp-content/themes/
      - ../courses:/var/www/html/wp-content/plugins/courses/ # Mount plugin directory
      - ../plc-plugin:/var/www/html/wp-content/plugins/plc-plugin/ # Mount plugin directory
      - ../docker/php.ini:/usr/local/etc/php/conf.d/custom.ini
    working_dir: /var/www/html

  db:
    image: mysql:8.0
    container_name: wp_db
    restart: always
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - '3306:3306'

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: wp_phpmyadmin
    restart: always
    ports:
      - '8080:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db

volumes:
  db_data: {}
