name: Deploy WordPress Theme to InfinityFree

on:
  push:
    branches:
      - main # Deploys when pushing to main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm' # Enables caching of npm dependencies

      - name: Debug - List Files
        run: ls -R theme/plc-2025 # Confirms correct paths in logs

      - name: Cache npm dependencies
        uses: actions/cache@v3
        with:
          path: ~/.npm
          key: npm-${{ runner.os }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            npm-${{ runner.os }}-

      - name: Install Dependencies
        run: |
          cd theme/plc-2025
          npm ci  # Faster than npm install if package-lock.json is present

      - name: Build Theme Assets
        run: |
          cd theme/plc-2025
          npm run build

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./theme/plc-2025/ # Deploy full theme with built assets
          server-dir: /htdocs/wp-content/themes/plc-2025/
