name: Deploy Theme to InfinityFree

on:
  push:
    branches:
      - main # Triggers deployment when pushing to main branch

jobs:
  ftp-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Deploy to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          local-dir: ./theme/plc-2025/ # Only deploy the theme directory
          server-dir: /htdocs/wp-content/themes/plc-2025/
